version: "3.9"

services:
  frontend:
    image: jaydenturnerlang/nginx:YOUR_SHA
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend-1
      - backend-2

  backend-1:
    image: jaydenturnerlang/backend:YOUR_SHA
    container_name: backend-container-1
    ports:
      - "3001:3000"

  backend-2:
    image: jaydenturnerlang/backend:YOUR_SHA
    container_name: backend-container-2
    ports:
      - "3002:3000"


