services:
  frontend:
    image: jaydenturnerlang/nginx:5e045a1
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: jaydenturnerlang/backend:5e045a1
    container_name: backend-container
    ports:
      - "3000:3000"
