version: "3.9"

services:
  frontend:
    image: jaydenturnerlang/nginx:YOUR_SHA
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: jaydenturnerlang/backend:YOUR_SHA
    container_name: backend-container
    ports:
      - "3000:3000"

