upstream backend {
    server backend-container-1:3000;
    server backend-container-2:3000;
}

server {
    listen 80;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/ {
        proxy_pass http://backend;
        add_header X-Served-By $upstream_addr always;
    }
}

