events {}

http {
    upstream backend_servers {
        server backend-container-1:3000;
        server backend-container-2:3000;
    }

    server {
        listen 80;

        add_header X-Served-By $upstream_addr always;

        location / {
            root /usr/share/nginx/html;
            try_files $uri /index.html;
        }

        location /api/ {
            proxy_pass http://backend_servers;
        }
    }
}
